### PR TITLE
Generic Functions for Merge Sort (Recursive)

### PR DESCRIPTION
**Pull request by iamsimranjot**
I upgraded the "**mergeSort**" & "**merge**" function in the _Merge Sort Algorithm_ to make it generic if someone needed to use the recursive approach for this algorithm.

### CODE REVIEW

**Comment by vincentngo** [comment]
@iamsimranjot the changes looks good! Thanks! One **minor** thing, i'm nitpicking... I notice some of the code does not follow the 2 space indentation. Could you just quickly fix that by following [https://github.com/raywenderlich/swift-style-guide#spacing](this) and i'll go ahead and merge the PR. Thanks!

**Comment by iamsimranjot** [comment]
@vincentngo Thank You for the Info. I updated the code by following the 2 space indentation style.

**Comment by vincentngo** [comment]
@iamsimranjot the Travis test seems to be failing, could you look into that? Thanks

**Comment by iamsimranjot** [comment]
@vincentngo Yea It seems that all the checks have passed successfully.

**Comment by vincentngo** [comment]
@iamsimranjot sounds good! Thanks for that!

**Pull request merged**
