### PR TITLE
Add A* algorithm

### PR DESCRIPTION
**Pull request by alejandro-isaza**
### Checklist

- [x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description

Adds and efficient implementation of the A* algorithm using a hashed heap for the open list.

### CODE REVIEW

**Comment by JaapWijnen** [comment]
Is this ready for review or are you still working on it?

**Comment by aleph7** [comment]
I wanted to improve the readme but it's ready otherwise.

**Comment by JaapWijnen** [comment]
Alright! Is it ok if I wait for you to finish up the readme and then review it?

**Comment by aleph7** [comment]
Ok, it's ready!

**Comment by kelvinlauKL** [comment]
@JaapWijnen Could you follow up with this?

**Comment by gaming-hacker** [comment]
I merged this into my fork and there are a couple of minor issues to fix.

**Comment by alejandro-isaza-hs** [comment]
Can you elaborate?

**Comment by aleph7** [comment]
Can you elaborate?

**Comment by gaming-hacker** [comment]
the file contents.xcworkspacedata needed tweaking.  there's nothing wrong with your algorithm.

**Comment by kelvinlauKL** [comment]
Long time coming @alejandro-isaza - sorry for the wait. We're doing some spring cleaning, glad I finally got to this!

**Pull request merged**
