### PR TITLE
Convert RadixSort to swift3 syntax

### PR DESCRIPTION
**Pull request by taiheng**
Also added a playground and test.

### CODE REVIEW

**Comment by pbodsk** [comment]
Hmm...that seems to be "my" tests failing. I'll have a look...sorry 😄

**Comment by pbodsk** [comment]
Fixed the test in #355

Once again, sorry @taiheng

**Comment by taiheng** [comment]
Thanks, I'll merge those changes in.

**Comment by taiheng** [comment]
I've been a bit busy, I'll get back to fixing this PR later today. (Jan 12)

**Comment by taiheng** [comment]
PR is now passing tests and ready to go.

**Comment by vincentngo** [comment]
@taiheng reviewing this!

**Pull request merged**
