### PR TITLE
finalize migration tests

### PR DESCRIPTION
**Pull request by JaapWijnen**
I noticed some of the tests haven't been uncommented in .travis.yml so updated that. Just need to check if everything still builds. And then I think we can close the migration issue #181 ?

### CODE REVIEW

**Comment by JaapWijnen** [comment]
Fixed most travis errors but Priority Queue is still giving me one. Can't seem to figure out what it is any ideas @vincentngo  @kelvinlauKL ?

**Comment by vincentngo** [comment]
@kelvinlauKL  @JaapWijnen restarting the build to see what happens but the error seems to be:

`Fix WWDRCA Certificate Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"security: AppleWWDRCA.cer: already in /Library/Keychains/System.keychain
`

**Comment by JaapWijnen** [comment]
@vincentngo Not sure what to do about that :/

**Comment by vincentngo** [comment]
@JaapWijnen Seems like there is also some conflicting files, could you try to resolve that?

**Comment by JaapWijnen** [comment]
I think that does it! Waiting for the build to complete. @vincentngo

**Comment by vincentngo** [comment]
@JaapWijnen sounds good. That was weird. i thought i saw no conflicts before. After running the build a second time it then showed conflicts.

**Pull request merged**
