### PR TITLE
Improvement of Ordered Set and Sorted Set

### PR DESCRIPTION
**Pull request by remlostime**
### Checklist

- [X] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description
* Add doc for apple ordered set
* Split ordered set (rename to sorted set) and apple ordered set (rename to ordered set)

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
It's a bit confusing for readers to see "Ordered Set" and "Apple Ordered Set". I suggest we append the explanations you have here with our old writeup.

**Comment by remlostime** [comment]
@kelvinlauKL Will do

**Comment by remlostime** [comment]
Now move the code and doc back to ordered set folder

**Comment by remlostime** [comment]
@kelvinlauKL I think the current `NSOrderedSet` should be named `NSSortedSet`. And this one should be the `NSOrderedSet`. What do you think?

**Comment by kelvinlauKL** [comment]
@remlostime Good point. I took a look at `NSOrderedSet` and you're right; I think the current version should be named `Sorted Set` and your version should be named as `Ordered Set`. 

Ordered sets don't necessarily have to be ordered in ascending order; The elements just need to stay "in-order" based on where they are inserted. 

In light of that, it actually makes sense to separate sorted set and ordered set to different folders, and make a clearer distinction in the explanations.

**Comment by remlostime** [comment]
Will update this PR.

**Comment by remlostime** [comment]
@kelvinlauKL Updated the PR. PTAL

**Comment by remlostime** [comment]
@kelvinlauKL Could you take another look at this?

**Comment by kelvinlauKL** [comment]
@remlostime Yes! Will follow up.

**Comment by kelvinlauKL** [comment]
Looks good, thanks!

**Pull request merged**
