### PR TITLE
Palindrome Checking Algorithm

### PR DESCRIPTION
**Pull request by srutstein21**
I've seen Palindrome Checking Algorithm questions in programming interviews before, and thought it would be a nice, quick addition to the Puzzle section here.

### CODE REVIEW

**Comment by Jxrgxn** [comment]
@srutstein21 Nice! Actually the algorithm I'm implementing is the solution to an obscure, and unintuitive substring palindrome problem. If you're interested in working on more toy problems you should check out my repo, Swift Cake: https://github.com/Jxrgxn/Swift-Cake

Still need to clean up the read me a lot and put in some O(n) charts. Anyways, great work .

**Comment by srutstein21** [comment]
Hey @Jxrgxn, do you mean that the read me for this branch needs work? What else should/needs to be added to the read me? Let me know and I'll get to it tonight hopefully. Thanks for the feedback!

**Comment by Jxrgxn** [comment]
@srutstein21 Oh no I meant my read me for my repo. Pardon the misunderstanding.

**Comment by kelvinlauKL** [comment]
@srutstein21 Looks good!

Just a few changes:

* changed `NSCharacterSet.whitespaceCharacterSet()` to just `.whitespaceCharacterSet()` as Swift can infer where that method is called
* modified `if length < 1` check to `guard length >= 1` check for a Swiftier solution.

**Pull request merged**
