### PR TITLE
Depth first search

### PR DESCRIPTION
**Pull request by JulioBBL**
### Checklist

- [x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description

 

The class Graph, is a representation of a Digraph, which is a Graph with oriented edges, a normal Graph would have two way edges

### CODE REVIEW

**Comment by vincentngo** [comment]
@JulioBBL It seems like you just changed the name from **Graph** to **Digraph**, i'm not sure if I see any real benefit with this. Could you please elaborate?

**Comment by remlostime** [comment]
I think graph could be two ways or one way. `Digraph` is kind of hard to understand what's `Di` mean?

**Comment by vincentngo** [comment]
@JuIioCesar closing this since I don't think changing just the name to Digraph makes any improvements to the implementation.

**Comment by JuIioCesar** [comment]
@vincentngo Wrong Julio cc: @JulioBBL

**Pull request closed without merging**
