### PR TITLE
Skip List

### PR DESCRIPTION
**Pull request by mitghi**
I am working on Skip List. It is almost finished.

### CODE REVIEW

**Comment by chris-pilcher** [comment]
Thanks @mitghi! 👍  Just let me know when it's ready for review. 

Would you be able to use this [style guide](https://github.com/raywenderlich/swift-style-guide) for writing code? E.g. change `private func find_head(key:Key)` to `private func findHead(key: Key)` and indent using 2 spaces.

**Comment by mitghi** [comment]
Thanks @chris-pilcher . I add the description very soon. 
And change the code style according to the style guide.

**Comment by kelvinlauKL** [comment]
@mitghi Looking to cleanup the pull requests. What's the ETA on this being completed?

**Comment by mitghi** [comment]
@kelvinlauKL I finish it this weekend.

**Comment by mitghi** [comment]
@kelvinlauKL @chris-pilcher The code is finished and refactored. Please have a look, so I can work on it faster in case anything should get changed. Documentation will be finished by tomorrow as well. Thanks

**Comment by mitghi** [comment]
@kelvinlauKL @chris-pilcher :) I appreciate if you provide some feedback so I can improve it.

**Comment by kelvinlauKL** [comment]
@mitghi Sorry for the delay. I just did a review on your code. Great job overall. 

* well done on the usage of `typealias` on the generic parameters. Makes the code much prettier
* nice work on generics
* good amount of diagrams. They really help others understand the concepts

A couple of comments:

```swift
// not preferred
fileprivate var array = [T]()

// preferred
fileprivate var array: [T] = []
```

All extensions should be preceded with a `// MARK: - Description of extension`. This provides some context on why you're grouping up the stuff in an extension.

A couple of compiler errors on the latest Xcode 8.0. In particular, the `coinFlip` doesn't compile correctly.

```swift
// not preferred
interval func insert(key: Key, data: Payload) { ... }

// preferred
func insert(key: Key, data: Payload) { ... }
```

Everything in your file is prefixed with an invisible internal. There's no need to explicitly state it.

```swift
public func remove(key: Key) -> Void { ... }
```

No need to specify the return type as `Void`.

```swift
self.head
```

```swift
self.head = Node(asHead: true)
```

No need to specify `self` explicitly to reference properties, unless compiler requires it.

**Comment by mitghi** [comment]
@kelvinlauKL Thank you very much Klevin, I modify it accordingly.

**Comment by kelvinlauKL** [comment]
@chris-pilcher Just letting you know I'm currently reviewing this.

**Pull request merged**
