### PR TITLE
Claim several data structures and algorithms for a group project

### PR DESCRIPTION
**Pull request by JFTung**
I am part of a group of four people.  Our final project for one of our classes is to contribute to an open source project.  We would like to work on this repository!  We will be working on several data structures and algorithms, and we'd like to claim some now.  Note that we will probably "claim" a few others later, depending on availability.

Currently "claimed" projects:
Trie
Radix Sort
Radix Tree
Red Black Tree
Threaded Binary Tree

### CODE REVIEW

**Comment by hollance** [comment]
Looking good! 

Note that counting sort is also being worked on by https://github.com/hollance/swift-algorithm-club/pull/103

**Comment by JFTung** [comment]
We've had to cut a few of the data structures due to time constraints (updated in my original comment), but our project is due May 6, so expect us to be done by then!

**Comment by hollance** [comment]
Only a few days left... :-D

**Comment by JFTung** [comment]
Quick update:  I've finished the Threaded Binary Tree, and Steven told me he finished his work on the Radix Tree.  My other partners are still working on Trie, Bucket Sort, and Red Black-Trees.  There's no deadline on when we need our branch accepted and actually merged, so whenever we finish please take your time looking it over if you wish!

**Comment by hollance** [comment]
Sure. Note that another Bucket Sort was already added in the mean time. This is no problem, but you may want to rename your folder to "Bucket Sort 2" in order to avoid merge conflicts.

**Comment by JFTung** [comment]
Sorry, that was a typo!  My partner is doing Radix Sort, not Bucket Sort.

**Comment by hollance** [comment]
In any case, there are merge conflicts somewhere, so it would be good if you could fix those. :-)

**Comment by JFTung** [comment]
We should be ready for you to look over our work!  I know that we're missing Playgrounds and unit tests, but I hope that our contribution is helpful in some way.  Let us know what's good, what's bad, and what we can do to make your life easier.

**Comment by axptwig** [comment]
I'm still working on Red Black Trees, i need to fix a bug delete and make the implementation adhere to the style guide

**Comment by Thukor** [comment]
I won't be able to provide test files tonight, but as of now there should only be minor bugs (if any) in the implementation for Trie (assuming I didn't mess up big time somewhere).

**Comment by hollance** [comment]
Starting to look good, guys! :-) 

Some small points:

- Can you rename the folder "Radix-Sort" to "Radix Sort" (drop the -)?
- Can you rename the folder "Red Black Trees" to "Red-Black Tree" (drop the s and add the -)?
- The Red-Black Tree seems not to take advantage of Swift's optionals. There's a lot of ! in there. It would be better to use `if let` to unwrap those, that is more Swift-like.
- The () are not necessary with if, so instead of `if (something)` you can simply write `if something`.
- Where did you get the images for Red-Black Tree and Threaded Binary Tree from? Did you make these yourself or did you copy them from somewhere? If the latter, please make sure you only use images whose license allows it and include a reference to the original. (We want to avoid any copyright violations.)

Let me know when you're done and I'll do the merge.

**Comment by JFTung** [comment]
The folder names should be good now, and the if parentheses have been removed from all but the Red-Black Tree files.  I made the Threaded Binary Tree images using www.draw.io, as mentioned at the bottom of the README.  I'm not sure where my partner got the Red-Black tree images from.  I'll get back to you.

**Comment by hollance** [comment]
Quick announcement: this repo is moving to https://github.com/raywenderlich/swift-algorithm-club -- everything should still work as before but some old links may not work anymore.

**Comment by JFTung** [comment]
Quick update, @axptwig is still working on the Red-Black tree fixes, but other than that we should be all set.

**Comment by chris-pilcher** [comment]
This looks great! 👍  

@JFTung @axptwig are you still working on the Red-Black tree fixes? Also, did you find out where the Red-Black images came from?

**Comment by JFTung** [comment]
Hi!  I've lost contact with @axptwig, but if you want we can separate our different data structures into different forks so you can choose what you want to pull (l can make a new pull request).

**Comment by chris-pilcher** [comment]
Thanks for the update @JFTung. I can merge this as a single pull request. I will do this tonight.

**Comment by JFTung** [comment]
Excellent, thank you!  Let me know if you need anything else.

**Pull request merged**
