### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by jherna37**
My native programming language is Java and I am new to swift.  To the best of my knowledge I have translated from Java to Swift. Thanks for the opportunity and don't be afraid to hurt my feelings. I'm open to any feedback. This was merely the first step of many.

### CODE REVIEW

**Comment by hollance** [comment]
Swift 3.0 is going to come out later this year and it removes this kind of for loop:

`for var j = 0; j < array.count; j++`

I also think you can get rid of the `if i + 1 < count` line if you make the loop for `i` go from `0` to `count-1`.

You can swap two array elements in Swift with: `swap(&a[i], &a[j])`, so no need to use a temporary variable.

It is possible to make the bubble sort a little bit more efficient: if no swap was necessary, then the sort is done and you can exit the loop.

That should give you something to do. ;-)

**Comment by hollance** [comment]
@jherna37: Is this something you're willing to work on some more?

**Comment by jherna37** [comment]
Hey sorry for the delay. I just finished my mid term exams and haven't had
much time since my first submission to work on it.

**Comment by hollance** [comment]
No worries. I'll just leave this open until you get a chance to work on it again.

**Comment by jherna37** [comment]
Just for clarification, would you like me to implement this algorithm without the use of for loops?

**Comment by hollance** [comment]
You can still use for loops, but it must be `for in`, not `for var i = ...; ... ; ...` since the latter is now deprecated in Swift.

**Comment by jherna37** [comment]
I've made the changes to the code. I was wondering if instead of radix sort you'd be open to more algorithm interview questions. I have a few examples from an interview I just came back from and think they'll make a nice addition.

**Comment by hollance** [comment]
Have you actually tried out those changes? I'm pretty sure it doesn't work like that...

Interview questions are very welcome! We already have a few simple ones, but more is better. :-)

**Comment by chris-pilcher** [comment]
Hi @jherna37. We're in the process of cleaning up our pull requests.

Would you still like to work on the bubble sort algorithm?

**Comment by kelvinlauKL** [comment]
Closing this due to inactivity. @jherna37 feel free to open another PR if you're up for another shot!

**Pull request closed without merging**
