### PR TITLE
Minimum edit distance for strings

### PR DESCRIPTION
**Pull request by herrlui**
Hi! 
I implemented the usual minimum edit distance algorithm for strings using the Levenshtein distance. I also plan to extend this implementation such that the algorithm can use arbitrary distance measures (as for example keyboard lookup tables).

### CODE REVIEW

**Comment by hollance** [comment]
Cool. :-) Could you also add an explanation of how this works?

**Comment by herrlui** [comment]
I have added a README. However, this is tentative since in a next step I will generalize the algorithm for more operations and costs.

**Comment by hollance** [comment]
Thanks. I'll wait with merging until you're done. :-)

**Comment by hollance** [comment]
Quick announcement: this repo is moving to https://github.com/raywenderlich/swift-algorithm-club -- everything should still work as before but some old links may not work anymore.

**Comment by chris-pilcher** [comment]
Hi @herrlui. Would you still like to make more changes before this is merged? 😃

**Comment by herrlui** [comment]
Hi! Sorry for the delay! I still plan to extend my code as soon as I find some time! :)

**Pull request merged**
