### PR TITLE
GitHub Pages

### PR DESCRIPTION
**Pull request by aquarchitect**
### Checklist

- [x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description

 

This pull request is based on #640.

The script requires 2 environment variables to run on Travis CI:
- _USERNAME_ - username of the repository's owner, __raywenderlich__ in your case.
- _TOKEN_ - personal access token with __public_repo__ permission.

> The token is used only within the script for the 2 following purposes:
> - Increase the limit of network calls to GitHub API Markdown to 5000 per hour (unauthenticated request caps at 60).
> - Push to __gh-pages__ remote branch.

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
Thanks @aquarchitect!

@vincentngo could you follow up with this?

**Comment by vincentngo** [comment]
@aquarchitect merging to see if this works.

**Comment by vincentngo** [comment]
@kelvinlauKL @aquarchitect waiting on the personal access token.

**Comment by aquarchitect** [comment]
@kelvinlauKL please keep me informed on the progress. 

The script to generate the page works locally. If you'd like to try, you can run it on a Mac or inside a Linux Docker container (for self-containing reasons). 

On TravisCI, however, sometimes builds just exit at one of the tests without any reason or any helpful log. Here is [the last one](https://travis-ci.org/aquarchitect/swift-algorithm-club) that TravisCI did on my fork. The [GitHub page](https://aquarchitect.github.io/swift-algorithm-club/) from my fork was generated and pushed manually.

Any idea/suggestion to make this working would be awesome.

**Comment by aquarchitect** [comment]
@kelvinlauKL @vincentngo 

The script ran in the last build - [https://travis-ci.org/raywenderlich/swift-algorithm-club](https://travis-ci.org/raywenderlich/swift-algorithm-club). Now we just need the token to push to __gh_pages__ branch.

I can't wait for it to be live. 😄

**Comment by vincentngo** [comment]
@aquarchitect https://github.com/raywenderlich/swift-algorithm-club/tree/gh-pages
I just added the necessary username and tokens. Is there a way we can make this like .io/gh-pages?

**Comment by vincentngo** [comment]
@aquarchitect I guess this works: https://cdn.rawgit.com/raywenderlich/swift-algorithm-club/gh-pages/index.html

**Comment by aquarchitect** [comment]
@vincentngo ya, the page is available at [http://raywenderlich.github.io/swift-algorithm-club/](http://raywenderlich.github.io/swift-algorithm-club/).

**Comment by vincentngo** [comment]
@aquarchitect oh yea for sure! It could be as good as Big O Cheat sheet.

**Comment by aquarchitect** [comment]
@vincentngo I make some changes to the script to do the following:
- Move inline css to the main stylesheet.
- Add responsive margin to the body.
- Add title to the header.
- Replace generated _index.html_ with a parsed one from the main repo's _README.markdown_.
- Parse other markdown files under _Important Links_ section.

Do you know if the main README links to all of the algorithm articles?

Check out the result [https://aquarchitect.github.io/swift-algorithm-club/](https://aquarchitect.github.io/swift-algorithm-club/). 

It would be awesome if you have any idea/suggestion. Let me know if I can go ahead with a PR.

**Comment by vincentngo** [comment]
@aquarchitect yea! this is a good start!

**Comment by aquarchitect** [comment]
@vincentngo Should I do a PR?

**Comment by vincentngo** [comment]
Yes please do!

**Comment by aquarchitect** [comment]
@vincentngo thanks for merging so quick. What else do you think I can do to improve the GitHub pages?

**Comment by vincentngo** [comment]
I think this is great for now, let's see how much traction this gets. Planning to announce this in the next SAC article. Thanks for all your work! Overall I think this is really cool! @kelvinlauKL thoughts? We could definitely work on beautifying this even more in the future. We could open another issue/enhancement to discuss with the community further!

**Comment by aquarchitect** [comment]
@vincentngo My end goal is to structure this like a book and create an ePub to read offline. Unfortunately, I don't know how to use __Pandoc__ and __Calibre__ properly to make a nice looking ePub 😞. So my thinking logic is eventually figuring out how to use pandoc/calibre to convert HTML to ePub.

**Comment by kelvinlauKL** [comment]
Awesome progress 👍 

Excited to see the future of this!

**Pull request merged**
