### PR TITLE
Implment KDTree

### PR DESCRIPTION
**Pull request by johnsgill3**
Working on implementing the KDTree structure. Need this algorithm for the implementation of #48. Will let you know when ready for review.

### CODE REVIEW

**Comment by hollance** [comment]
Cool. I was thinking maybe the folder should be "kd-Tree", since the regular spelling is k-d tree or kd-tree.

**Comment by johnsgill3** [comment]
Sure I'll call it KD-Tree. I'm not picky.

**Comment by chris-pilcher** [comment]
Hi @johnsgill3. Just checking in. We're in the process of cleaning up our pull requests. Are you still interested in implementing the KDTree structure?

**Comment by kelvinlauKL** [comment]
Doing a cleanup of inactive PRs. If you're still interested in writing this, feel free to remake the PR!

**Pull request closed without merging**
