### PR TITLE
Naive Bayes Classifier

### PR DESCRIPTION
**Pull request by ph1ps**
Now this is just the first step of the process from the "How to contribute.md" (I still need a writeup and some code cleaning). Therefore this is just a "claim" so no one else invests time on it. 
Thanks!

### CODE REVIEW

**Comment by ph1ps** [comment]
I'm ready for review!

**Comment by vincentngo** [comment]
@ph1ps was this closed by accident?

**Comment by ph1ps** [comment]
@vincentngo Oops, sorry. Thanks for noticing.

**Comment by vincentngo** [comment]
@ph1ps sorry for the delay, this is next on my plate!

**Comment by ph1ps** [comment]
@vincentngo No problem, I didn't want to stress you, I was just looking through the PR on my phone and I might have clicked on close. I'm doing the next classifier right now anyways. :]

**Comment by ph1ps** [comment]
@vincentngo Haha yeah true but this in that case it was very hard to come up with a name other than `class`

**Comment by vincentngo** [comment]
@ph1ps still good to understand how they work :)

**Pull request merged**
