### PR TITLE
Fixes Issue#371: Simulated Annealing demo crashes

### PR DESCRIPTION
**Pull request by dynamite8**
\### Checklist

- [ X] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [ ] This pull request is complete and ready for review.

### Description

Updated code based on Xcode 10 beta version.  This is not the current version supported by SAC but in case we move towards Xcode 10 in the future, this is here.

Asking the original issue opener to review this.

### CODE REVIEW

**Comment by pstoehr** [comment]
From my point of view the bug is still there!
As mentioned in the online documentation, the swap() routine should not be used for mutable collections. If two elements of mutable collection should be swapped, swapAt() have to be used!

**Comment by dynamite8** [comment]
@pstoehr - there were compilation errors so those are fixed in this PR now.  How are you running this?  Can you pass the details?  If it's only needed to change the methods, then that should be easy.

**Comment by kelvinlauKL** [comment]
These changes look good with respect to Xcode 10.0. 

I think the author of this algorithm is running on Linux, thus there wasn't an Xcode playground accompanying this. 

@dynamite8 would you be interested in authoring a playground for this topic?

**Comment by kelvinlauKL** [comment]
Merging this for Xcode 10.0 compatibility. @pstoehr I'll leave the #731 issue open for further discussion.

**Comment by pstoehr** [comment]
Come on folks, It seems that you've included a **new bug**!
The method shuffle() of the extension of the class Tour calls itself with an endless recursion!

To find this bug I just downloaded the file simann_example.swift, created a new Xcode project using Version 10.0 beta 5. Than 
    Compile -> Run -> Crash

By the way, the compiler gives the warning "All paths through tis function will call itself" and this is a strong hint that you have an endless recursion!

From my point of view the implementation should look like 
```
    func shuffle() {
        tour.shuffle()
    }
```
Would you please be so kind to check whether this really fixes the bug!

**Pull request merged**
