### PR TITLE
Set Cover (Unweighted)

### PR DESCRIPTION
**Pull request by mrael2**
I've written the code for the Greedy Set Cover algorithm (unweighted), and I'm starting to work on the explanation in the README.

I'll let you know when I'm done (hopefully within one week).

### CODE REVIEW

**Comment by chris-pilcher** [comment]
Thanks @mrael2. This looks great! Just let me know when you are ready to merge.

**Comment by mrael2** [comment]
I'm done with documentation and ready to merge. Thanks, @chris-pilcher

**Comment by chris-pilcher** [comment]
Thanks @mrael2! Sorry for the delay. I'll review and look at merging now.

**Comment by chris-pilcher** [comment]
Thanks! :D This looks great! I will merge now.

**Pull request merged**
