### PR TITLE
Single-Source Shortest Paths (Weighted)

### PR DESCRIPTION
**Pull request by armcknight**
- [x] rename preexisting `Shortest Paths (Unweighted)` directory to `Single-Source Shortest Paths (Unweighted)`, for clarity to distinguish it from All-Pairs Shortest Paths, and for consistency with the one I will add (`Single-Source Shortest Paths (Weighted)`)
- [x] Refactor the Graph data structure for better use between directed and undirected cases
- [x] Bellman-Ford Algorithm
- [ ] Dijkstra's Algorithm with priority queue

### CODE REVIEW

**Comment by armcknight** [comment]
This diff currently has a bunch of other commits because I branched off the HEAD of another branch waiting to be merged (#109). Will rebase onto master when that is merged.

**Comment by hollance** [comment]
Quick announcement: this repo is moving to https://github.com/raywenderlich/swift-algorithm-club -- everything should still work as before but some old links may not work anymore.

**Comment by armcknight** [comment]
thanks for the heads up @hollance. who is the new point person?

**Comment by hollance** [comment]
That would be @chris-pilcher and @kelvinlauKL

**Comment by armcknight** [comment]
i'm going to close this in favor of #125, the changeset is getting too big and I decided to implement Bellman-Ford first, so the branch name is more accurate of the work being done there than here. Will open a separate PR for Dijkstra's algorithm.

**Pull request closed without merging**
