### PR TITLE
updated Linked List by optimize tail node and count

### PR DESCRIPTION
**Pull request by hupei1991**
### Checklist

- [x ] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [ x] This pull request is complete and ready for review.

### Description

 
I updated the Linked List data structure. Because the time complexity of previous version is O(n) to get the tail node and count the total number of node. I updated this to get these in time complexity of O(1). Because this is the actually optimal solution for double linked list, which make O(n) solution a little bit misleading.

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
Hey, thanks for the suggestion!

You're right to say that the current implementation is not the optimal solution for a LinkedList. However, the author intentionally left out the tail reference for the sake of showing what operations need to happen without it. 

If you really want to include the tail reference, we'll need to do a bigger refactor of the text to help the prose flow from the tail-less world.

**Comment by hupei1991** [comment]
Should we do the refactoration upon the tutorial text? Because when someone was trying to use this piece of code in their own code base, the original implementation would be misleading and even causing performance problem.

**Comment by kelvinlauKL** [comment]
To be fair, I don't think the current tutorial is misleading. The goal is to introduce the reader to the singly linked list - which includes all of the challenges with backwards iteration. The author notes these drawbacks in the beginning:

>A singly linked list uses a little less memory than a doubly linked list because it doesn't need to store all those previous pointers.
>
>But if you have a node and you need to find its previous node, you're screwed. You have to start at the head of the list and iterate through the entire list until you get to the right node.
>
>For many tasks, a doubly linked list makes things easier.

I'd like to preserve the author's original intention of showing what a singly linked list is about. There's also a few notes throughout the text alluding to how a previous / tail reference could optimize the performance of the list. IMO this approach does provide value to the reader.

Perhaps we could just add a new file with the optimizations and add a section near the end telling the reader what the optimized version looks like?

If you're up for a bigger task, adding a separate entry for the doubly linked list might make sense as well.

**Comment by kelvinlauKL** [comment]
#864 also discusses this

**Comment by richard-ash** [comment]
Closing due to inactivity. If you reopen we're happy to take another look :)

**Pull request closed without merging**
