### PR TITLE
Add variety implementation with complexity analysis.

### PR DESCRIPTION
**Pull request by antonio081014**
### Checklist

- [x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description

 
This PR added more implementation of UnionFind algorithms with complexity analysis added by the end of README file.

### CODE REVIEW

**Comment by antonio081014** [comment]
@kelvinlauKL, @vincentngo Any maintainers available to take a look at this PR?

**Comment by kelvinlauKL** [comment]
This looks good, but I just wanted a clarification on something. 

You used the word **variety**. I'm not familiar with this usage in this context. Did you mean to write a "variant of the implementation"?

**Comment by antonio081014** [comment]
Yes, have each implementation in a single swift file. These implementations demonstrate how this algorithm could be improved or implemented in some other way.

**Comment by kelvinlauKL** [comment]
Cool. This looks good to merge. Thanks!

**Pull request merged**
