### PR TITLE
Updating Select Minimum Maximum to Swift 3

### PR DESCRIPTION
**Pull request by emadhegab**

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
Could you also update the playground and the rest of the `README`?

**Comment by braveHeartBob** [comment]
Hi there！i am a newbIe for programmimg with swift，i don't know much about data structure and algorithms ，thanks for your working.
happy new year！best wishes！
On 01/01/2017 00:02, Kelvin Lau wrote:

Could you also update the playground and the rest of the README?

**Comment by emadhegab** [comment]
Done.. Thx

**Comment by kelvinlauKL** [comment]
@braveHeartBob On behalf of all the contributors here, your welcome! 

@emadhegab Thanks, changes look good. For future reference, we use 2 space indents for our code. I'll merge this anyway and change that for you.

Cheers!

**Pull request merged**
