### PR TITLE
Updating Stack to Swift 3

### PR DESCRIPTION
**Pull request by nemanjavlahovic**

### CODE REVIEW

**Comment by nemanjavlahovic** [comment]
Ready to be merged.

**Comment by chris-pilcher** [comment]
Thanks @nemanjavlahovic. Did you mean to comment out Array2D, AVL Tree & Binary Search from `.travis.yml`? If not, could you uncomment them?

**Comment by chris-pilcher** [comment]
A couple of other quick things: 
- Would you be able to quickly update the `Tests.xcodeproj` to the recommended settings? 
screen shot 2016-08-30 at 9 56 42 pm
- It looks like a couple of things in `README.markdown` need to be updated as well. I copied code from `README.markdown` into a new playground and received errors
screen shot 2016-08-30 at 10 01 23 pm

**Comment by nemanjavlahovic** [comment]
Hey @chris-pilcher , sorry for the inconvenience, fixed that too. I thought I already updated to recommended settings, not sure how this happened, but anyhow it is fixed now. I think it is ready to be merged. Thanks for the heads up!

**Comment by chris-pilcher** [comment]
Thanks heaps @nemanjavlahovic 👍

**Pull request merged**
