### PR TITLE
Bug fix palindromes

### PR DESCRIPTION
**Pull request by lostatseajoshua**
## PR Changes
This PR contains fixes for the palindrome algorithm based on the bug listed in #316.
The algorithm was redesigned as the current implementation did not support the case of palindromes containing punctuation, word dividers, and special characters.

### Content of changes
- [x] The README was updated to clarify the algorithm 
- [x] Playground test cases 
- [x] Code documentation

### CODE REVIEW

**Comment by lostatseajoshua** [comment]
Will be adding Travis CI tests soon.

**Comment by kelvinlauKL** [comment]
This is really good. I love the changes that you've made not only to the code, but also the examples and theory in the `README` file. The tests were a solid addition too. 

I don't see anything I want to change, but Travis seems to be failing.

**Comment by lostatseajoshua** [comment]
@kelvinlauKL thanks! The tests are fixed. The branch is ready to go on side let me know if anything else needs to be updated.

**Comment by kelvinlauKL** [comment]
Looks good. Merging this in. Thanks @lostatseajoshua!

**Pull request merged**
