### PR TITLE
Prime Numbers

### PR DESCRIPTION
**Pull request by tailec**
I'm planning to write algorithms for finding prime numbers using linear approach, atkin-bernstein sieve and eratosthenes sieve.

What's your opinion @hollance? Would it be useful?

### CODE REVIEW

**Comment by hollance** [comment]
Sounds like fun. :-) 

Any chance of including the method using the Lucas numbers? I just saw a video on that --- https://www.youtube.com/watch?v=lEvXcTYqtKU --- and it looked quite interesting.

**Comment by chris-pilcher** [comment]
Hi @tailec. Would you still like to work on these algorithms?

**Comment by tikipatel** [comment]
@tailec Not sure what algorithm you were going to use, but I have created a PR #139 that uses the Sieve of Eratosthenes.

**Comment by tailec** [comment]
Hey, sorry I was really busy lately. Going to push something soon.

**Comment by chris-pilcher** [comment]
Thanks for the update @tailec 😄  I'll leave this PR open.

**Comment by chris-pilcher** [comment]
Hey @tailec, I'm doing a cleanup of inactive PRs. If you're still interested in contributing feel free to remake a PR! Note: there is another active PR related to prime numbers #139.

**Pull request closed without merging**
