### PR TITLE
[FINISHED] 🌳  🌳   Splay Tree Implementation 

### PR DESCRIPTION
**Pull request by barbaramartina**
:deciduous_tree::deciduous_tree::deciduous_tree::deciduous_tree:
# **FINISHED**

## Finished
- :heavy_check_mark: Implementation 
- :heavy_check_mark: Debugging :beetle:
- :heavy_check_mark: Tests project 
- :heavy_check_mark: Playground
- Documentation :green_book:

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
@vincentngo What's the plan regarding this one and #240?

**Comment by vincentngo** [comment]
@kelvinlauKL I was hoping once @barbaramartina finishes this one, we can close #240

**Comment by kelvinlauKL** [comment]
Since #240 has been inactive for the last few months, let's close it and move forward on this one.

**Comment by barbaramartina** [comment]
Hi guys, are you taking over this ? The implementation is just in initial steps .  Neither debug is finished. Let's me know how you proceed usually so I avoid putting time if you're already going to continue with that. On my side I'm glad to continue but can not compromise to a short deadline.

**Comment by vincentngo** [comment]
hi @barbaramartina you can continuing working on this, thanks!

**Comment by barbaramartina** [comment]
@kelvinlauKL @vincentngo this PR is complete and ready to review. Documentation is finished and the SVG of the diagrams are updated in case you'd like to refine then further. 
I won't be available the next 1.5 / 2 months, but please make any review comments / change you'd like to this one. Was fun to know Splay Trees better!

**Comment by kelvinlauKL** [comment]
Reviewing this is long overdue! I've read the readme, great work. I'll get this merged once I do a code review.

**Comment by kelvinlauKL** [comment]
@barbaramartina Thanks for the contribution! It was a pleasure to read and look at the code.

**Pull request merged**
