### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by Parva9eh**
Hello,
I have revised one of your documents for my assignment. I still need to revise more documents (10 in total). I hope it will be fine if I choose some documents from your account.
Thanks,
Parvaneh

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
@Parva9eh 

There seems to be some merge conflicts (probably due to the ongoing percent encoding changes). Could you fix the conflicts?

**Comment by Parva9eh** [comment]
Thanks. I have fixed the conflicts.

**Comment by kelvinlauKL** [comment]
👍

**Comment by Parva9eh** [comment]
@kelvinlauKL Thanks.

**Pull request merged**
