### PR TITLE
update Shuffle for Swift 3

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by chris-pilcher** [comment]
Thanks @TheIronBorn! 👍  Looks good so far. 

Would you be able to update `Shuffle.playground` and `README.markdown`?

**Comment by TheIronBorn** [comment]
Can do

**Comment by TheIronBorn** [comment]
I've updated the source code in those files.
I'm not sure if I did the Github stuff correctly but I hope you can find the changes I've made. Also I'm not sure what to do with the metadata files in `Shuffle.playground`

**Comment by kelvinlauKL** [comment]
#273 and #274 seems to address this, created by the same author. Going to close this one since I merged the other two @TheIronBorn. Thanks!

**Pull request closed without merging**
