### PR TITLE
Bellman-Ford Single Source Shortest Paths (weighted)

### PR DESCRIPTION
**Pull request by armcknight**

### CODE REVIEW

**Comment by chris-pilcher** [comment]
Thanks Andrew 😄  This looks great so far! Let me know when it's ready for review.

Also, I created an [additional test for SSSP](https://gist.github.com/chris-pilcher/1788da1b00bb51be4f2f01542bb33efb) when I started looking through the changes. This gist might be useful if you're looking for additional test cases.

**Comment by armcknight** [comment]
Thanks @chris-pilcher. I'll definitely incorporate the test. I have a few tweaks to docs and a bugfix to push up, and i'm rounding out the readme. Hopefully done by this weekend!

**Comment by armcknight** [comment]
@chris-pilcher I think this is ready for a full review!

**Comment by chris-pilcher** [comment]
Thanks @armcknight! I will go through a full review tomorrow.

**Comment by chris-pilcher** [comment]
This looks awesome @armcknight! I have a couple of comments/questions before merging: 

- It looks like changing `Graph` to have an `AbstractGraph` has broken the `All-Pairs Shortest Paths` playground. Would you be able to have a look?
screen shot 2016-06-05 at 7 41 42 pm
- Would you be able to add the `Single-Source Shortest Paths (Weighted)` project to `.travis.yml` so the tests are run on our build server?
- Did you create the images yourself?

**Comment by armcknight** [comment]
@chris-pilcher Thank you so much for catching these things. Fixed the playground and added the tests to the .travis.yml.

As for the images, yes, I made them all with Sketch, although one example is the same graph from the textbook referenced, just reproduced from scratch.

**Comment by chris-pilcher** [comment]
Merged. Thanks @armcknight

**Pull request merged**
