### PR TITLE
Migrate Threaded Binary Tree to Swift 3

### PR DESCRIPTION
**Pull request by JaapWijnen**

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
@JaapWijnen Travis seems to have failed for this one.

**Comment by JaapWijnen** [comment]
@kelvinlauKL Hm strange, can't really see what's going wrong from the job log. Any ideas?

**Comment by JaapWijnen** [comment]
@vincentngo maybe any ideas what's going wrong?

**Comment by vincentngo** [comment]
@JaapWijnen looking

**Comment by vincentngo** [comment]
@JaapWijnen there is one warning, line 179. 
`successor.remove()`

Could you also make it 2 spaces and then try to submit again? I feel like the build stalled. If it doesn't work i'll take a deeper dive.

**Comment by JaapWijnen** [comment]
I hope #377 fixes this. So this can be closed.

**Pull request closed without merging**
