### PR TITLE
migrates Single-Source Shortest Paths to Swift 3 syntax

### PR DESCRIPTION
**Pull request by pbodsk**

### CODE REVIEW

**Comment by pbodsk** [comment]
hi @vincentngo 

I would love to do so....but I'm terribly sorry, I'm not sure I understand what you mean. The `SSSP Test Target` has been converted to Swift 3 as well.

Where do I toggle the legacy code setting?

Is it this?

screen shot 2017-01-14 at 09 28 06

**Comment by vincentngo** [comment]
@pbodsk yup that's right. The reason why is because when someone opens the xcworkspace, it will show a popup saying " Would you like to convert to latest Swift", but you already did it! :)

**Comment by pbodsk** [comment]
@vincentngo OK...and should that be set to `no`?

**Comment by vincentngo** [comment]
@pbodsk yup

**Comment by vincentngo** [comment]
@pbodsk i'm going to go ahead and merge this, and set the flag for you 👍  since it's trivial

**Comment by pbodsk** [comment]
Thanks @vincentngo

**Pull request merged**
