### PR TITLE
Swift 3 Migration

### PR DESCRIPTION
**Pull request by NeilNie**
- Graph, ASAP, Single-Source Shortest Paths (Weighted) migrated to
  Swift 3.
- Xcode project setting updated.
- Other small changed generated by Xcode 8.1

### CODE REVIEW

**Comment by NeilNie** [comment]
I also made a new commit with several new Swift 3 migrations. 

- BinarySearchTree
- BinarySearchTreeTest
- BreathFirstSearch Edge, Graph, Node, Queue
- kMeans
- kMeans test
- Minimum Spanning Tree
- Two-Sum Problem both solutions
- Other small changes generated by Xcode

**Comment by kelvinlauKL** [comment]
@NeilNie I just took a look at this. It seems like you had an older version of the master. Some of the algorithms you've done migrations for has been completed already.

For instance, the Binary Search Tree algorithm was updated a month ago with 6ee811901e79b860c443f8bd8ea3ccfecd9f08ba

The overall code conversion looks about right, though there are a few styling suggestions I want to add. 

```swift
// not preferred
private class EdgeList<T> where T: Equatable, T: Hashable { ... }

// preferred
private class EdgeList<T: Hashable, Equatable> { ... }
```

Also, it looks like none of the `README` files are updated. We'll need those updated with the code changes as well.

I'll also really appreciate if you could break up the changes into their own PRs. It's fairly difficult to review 83 files at once! Otherwise, I appreciate the time you put into migrating so many of these.

**Comment by NeilNie** [comment]
@kelvinlauKL Thank you very much for your thoughtful reply. I will keep your suggestions in mind and try to update the READMEs.

**Comment by kelvinlauKL** [comment]
@chris-pilcher Could you follow up on this? Travis seems to have broke.

**Comment by kelvinlauKL** [comment]
@NeilNie 

I apologize for the late response on this PR. All of the changes have since been migrated over to Swift 3, so I'll close this PR now.

**Pull request closed without merging**
