### PR TITLE
LFU

### PR DESCRIPTION
**Pull request by remlostime**
### Checklist

- [x] I've looked at the [contribution guidelines](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.github/CONTRIBUTING.md).
- [x] This pull request is complete and ready for review.

### Description

LFU cache is more complicate than LRU. I give the solution here.

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
Could you add this to the LRU writeup instead? They're so closely linked together, and you're already referring to the LRU article in the readme.

**Comment by remlostime** [comment]
@kelvinlauKL No problem.

**Comment by remlostime** [comment]
Improve the readme and move it back to LRU and LFU folder

**Comment by remlostime** [comment]
@kelvinlauKL PTAL. Rebased.

**Comment by remlostime** [comment]
@kelvinlauKL Could you take another look?

**Comment by kelvinlauKL** [comment]
Hey @remlostime. Sorry for the long wait for a response. 

We've updated our guidelines to focus submissions to the Swift Algorithm Club on general purpose algorithms & data structures. Unfortunately, this PR is an interview-style submission, and so we are closing it as it does not fall under the general category.

**Pull request closed without merging**
