### PR TITLE
Ring buffer swift3 migrate

### PR DESCRIPTION
**Pull request by JaapWijnen**
Migrate Ring buffer to swift3 for #181

### CODE REVIEW

**Comment by chris-pilcher** [comment]
Thanks @JaapWijnen 😄 Looks great so far! 

Would you be able to update the implementation of `RingBuffer` in the `README.markdown`?

**Comment by JaapWijnen** [comment]
@chris-pilcher Done!

**Comment by kelvinlauKL** [comment]
Looks good @JaapWijnen!

**Comment by JaapWijnen** [comment]
Normally you would, and make some functions for accessing the private values you need. But as it's embedded in a playground and all these extra functions are kind of distracting from the actual way the data structure works I omitted it. And thus I had to make them fileprivate so I could play around with them in the playground.

**Comment by JaapWijnen** [comment]
@BenEmdon Normally you would, and make some functions for accessing the private values you need. But as it's embedded in a playground and all these extra functions are kind of distracting from the actual way the data structure works I omitted it. And thus I had to make them fileprivate so I could play around with them in the playground.

**Pull request merged**
