### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by Moon1102**
add swift version

### CODE REVIEW

**Comment by kelvinlauKL** [comment]
@Moon1102 Adding the Swift sample code is a good idea. Though, I noticed your implementation is different from the code in the project. We should keep the 2 consistent.

**Comment by kelvinlauKL** [comment]
Just to follow up, could you update the code snippet you added with the one that's currently written in the Swift file?

**Comment by Moon1102** [comment]
Sure. I was already found the difference between the two codes,and I tried to improve my code.

**Comment by Moon1102** [comment]
I pull new request,#392.  I'm sorry about my English is not well.

**Comment by kelvinlauKL** [comment]
@Moon1102 Could you update this `README` to match the implementation from #392?

**Comment by Moon1102** [comment]
Sure. I'll be glad to do it.

**Comment by kelvinlauKL** [comment]
Looks good. Thanks @Moon1102!

**Comment by Moon1102** [comment]
@kelvinlauKL  You're welcome.

**Pull request merged**
