### PR TITLE
Ternary search tree

### PR DESCRIPTION
**Pull request by Satre95**
I've started work on the Ternary Search Tree data structure. I should have it finished in a few days.
Reference issue #83

### CODE REVIEW

**Comment by Satre95** [comment]
Update: The tree data structure has been implemented. A simple test in the playground has been implemented as well. 
Documentation and examples coming soon!

**Comment by hollance** [comment]
Nice!

**Comment by Satre95** [comment]
Update: Added Documentation to source code.

**Comment by Satre95** [comment]
Apologies for the delay, college started again. I plan to write the README this weekend.

**Comment by chris-pilcher** [comment]
Hi @Satre95. Thanks for the contribution! I'll merge what you have so far into our new [Under Construction](../blob/master/Under Construction.markdown) area. 

When you write the readme please add a new pull request 😄

**Comment by Satre95** [comment]
@chris-pilcher  Thanks. I will write the README in another week.

**Pull request merged**
