### PR TITLE
Migrate Shunting Yard to Swift 3

### PR DESCRIPTION
**Pull request by JaapWijnen**

### CODE REVIEW

**Comment by vincentngo** [comment]
@JaapWijnen thanks for the PR, could you please have the code conform to the two spacing convention. This is based on the swift style guidelines we are using.

**Comment by JaapWijnen** [comment]
Sorry for some reason I can't access my code from the PR anymore don't really know what's going on

**Comment by kelvinlauKL** [comment]
@JaapWijnen I'll handle the 2-space indenting. Thanks!

**Comment by JaapWijnen** [comment]
thanks! wasn't that fast sorry ;)

**Pull request merged**
